# Generated by Django 3.2.18 on 2023-04-18 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Название резюме')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(default=None, max_length=100, verbose_name='Фамилия')),
                ('date_birth', models.DateField(default=None, verbose_name='Дата рождения')),
                ('home_town', models.CharField(default=None, max_length=80, verbose_name='Город, где вы проживаете')),
                ('phone_num', models.CharField(default=None, max_length=50, verbose_name='Номер телефона')),
                ('job_position', models.CharField(default=None, max_length=100, verbose_name='Желаемая должность')),
                ('salary', models.PositiveIntegerField(default=None, verbose_name='Желаемая заработная плата')),
                ('skills', models.CharField(default=None, max_length=100, verbose_name='Профессиональные навыки')),
                ('about_me', models.TextField(default=None, verbose_name='О себе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
