# Generated by Django 3.2.18 on 2023-04-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
