# Generated by Django 3.2.18 on 2023-04-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy_parsed',
            options={'ordering': ['-created_date']},
        ),
    ]
