# Generated by Django 3.2.18 on 2023-04-25 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy_Parsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250, unique=True)),
                ('name_company', models.CharField(max_length=250)),
                ('adress_company', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('key_skills', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
