# Generated by Django 3.2.18 on 2023-04-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
