# Generated by Django 3.2.18 on 2023-05-26 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None, verbose_name='Начало работы')),
                ('end_date', models.DateField(default=None, verbose_name='Окончание')),
                ('company', models.CharField(default=None, max_length=100, verbose_name='Организация')),
                ('position', models.CharField(default=None, max_length=100, verbose_name='Должность')),
                ('responsibilities', models.TextField(default=None, verbose_name='Обязанности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default=None, max_length=200, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(default=None, max_length=200, verbose_name='Факультет')),
                ('specialization', models.CharField(default=None, max_length=200, verbose_name='Специализация')),
                ('graduation_year', models.DateField(default=None, verbose_name='Год окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
